name: WINDOWS 2022 RDP
on:
  workflow_dispatch:
    inputs:
      increment:
        type: string
        description: "Enter Your NGROK TOKEN"
        required: true
        default: ""
jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999
    steps:
      - name: Download Ngrok.
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/ngrok.exe -OutFile ngrok.exe
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg -OutFile wallpaper.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/loop.bat -OutFile loop.bat
      - name: Connect Ngrok.
        run: |
          ./ngrok.exe authtoken $Env:NGROK_AUTH
          echo ${{ github.event.inputs.increment }}
          echo $Env:NGROK_AUTH
        env:
          NGROK_AUTH: ${{ github.event.inputs.increment }}
      - name: Windows10 RDP.
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          copy wallpaper.bat D:\a\wallpaper.bat
      - name: Tunnel.
        run: Start-Process Powershell -ArgumentList '-Noexit -Command "ngrok.exe tcp --region ap 3389"'
      - name: Connect Rdp.
        run: cmd /c start.bat
      - name: win10 RDP.
        run: cmd /c loop.bat
